version: '3'

services:
  pg:
    image: postgres:latest
    restart: always
    volumes:
      - './data/db:/var/liv/pgdata/data'
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    networks:
      snova:
        aliases:
          - pg
    ports:
      - 5432:5432
  bot:
    build:
      context: ./bot
      dockerfile: Dockerfile
    restart: always
    networks:
      snova:
        aliases:
          - bot
    volumes:
      - './bot:/app'
    depends_on:
      - pg
  web-app:
    build:
      context: ./web-app
      dockerfile: Dockerfile
    restart: always
    networks:
      snova:
        aliases:
          - web-app
    ports:
      - '3000:3000'
    volumes:
      - './web-app:/opt/code'
  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8081
    networks:
      - snova
      - adminer


networks:
  snova:
    driver: bridge
  adminer:
    driver: bridge