version: '3'

services:
  pg:
    image: postgres:latest
    restart: always
    volumes:
      - './data/db:/var/liv/pgdata/data'
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    networks:
      snova:
        aliases:
          - pg
    ports:
      - 5432:5432
  bot:
    build:
      context: ./
      dockerfile: Dockerfile
    restart: always
    networks:
      snova:
        aliases:
          - bot
    volumes:
      - './:/app'
    depends_on:
      - pg
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      - snova
      - adminer


networks:
  snova:
    driver: bridge
  adminer:
    driver: bridge