"""add Request

Revision ID: 147f02521dab
Revises: 257cce35241f
Create Date: 2023-11-18 22:40:33.718030

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '147f02521dab'
down_revision: Union[str, None] = '257cce35241f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tg_id', sa.BigInteger(), nullable=False),
    sa.Column('fio', sa.String(), nullable=False),
    sa.Column('phone_numebr', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('request_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('address', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('date', sa.String(), nullable=False),
    sa.Column('time', sa.String(), nullable=False),
    sa.Column('cost_min', sa.Integer(), nullable=False),
    sa.Column('cost_max', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user_table.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('user')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('tg_id', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('fio', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('phone_numebr', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('adress', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='user_pkey')
    )
    op.drop_table('request_table')
    op.drop_table('user_table')
    # ### end Alembic commands ###
