"""add columns to User

Revision ID: 257cce35241f
Revises: 9c54af52befe
Create Date: 2023-11-18 19:00:42.831874

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '257cce35241f'
down_revision: Union[str, None] = '9c54af52befe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('fio', sa.String(), nullable=True))
    op.add_column('user', sa.Column('phone_numebr', sa.String(), nullable=True))
    op.add_column('user', sa.Column('adress', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'adress')
    op.drop_column('user', 'phone_numebr')
    op.drop_column('user', 'fio')
    # ### end Alembic commands ###
